Reworked the time system, moved things around a bit
l1ttleO/Boyfriend pull request #5
Opened 2021-08-19 03:00 UTC by Apceniy

2021-08-19 09:16 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +            channel.sendMessage("Указан недействительный пользователь!").queue();
this breaks build check for literally no reason

2021-08-19 10:57 UTC, l1ttleO requested changes

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +    public static <T> T plural(long amount, final T one, final T two_to_four, final T five_to_zero) {
```suggestion
    public static <T> T plural(long amount, final T one, final T twoToFour, final T fiveToZero) {
```
`Parameter name 'two_to_four' doesn't match regex '[a-z][A-Za-z\d]*'`
`Parameter name 'five_to_zero' doesn't match regex '[a-z][A-Za-z\d]*'`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +            return five_to_zero;
```suggestion
            return fiveToZero;
```
`Parameter name 'five_to_zero' doesn't match regex '[a-z][A-Za-z\d]*'`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +        return two_to_four;
```suggestion
            return one;
        return twoToFour;
```
`Parameter name 'two_to_four' doesn't match regex '[a-z][A-Za-z\d]*'`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +        final GregorianCalendar dateFrom = new GregorianCalendar();
`Obsolete date-time type 'GregorianCalendar' used`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +        final GregorianCalendar dateTo = new GregorianCalendar();
`Obsolete date-time type 'GregorianCalendar' used`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +        millisOfTheDay = Math.round(((float) millisOfTheDay) / 1000);
```suggestion
        millisOfTheDay = Math.round((float) millisOfTheDay / 1000);
```
`Parentheses around '((float) millisOfTheDay)' are unnecessary`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +                    continue;
`'continue' statement`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
>              }
```suggestion
                switch (unit) {
                    case Calendar.YEAR -> amount = dateTo.get(unit) - dateFrom.get(unit);
                    case Calendar.MONTH -> {
                        amount = dateTo.get(Calendar.MONTH) - dateFrom.get(Calendar.MONTH);
                        if (amount < 0) {
                            amount += 12;
                            durations.put(Calendar.YEAR, durations.get(Calendar.YEAR) - 1);
                        }
                    }
                    default -> { // DAY_OF_YEAR
                        amount = dateTo.get(Calendar.DAY_OF_MONTH) - dateFrom.get(Calendar.DAY_OF_MONTH);
                        if (amount < 0) {
                            amount = durations.getOrDefault(Calendar.MONTH, 12);
                            final int years = durations.getOrDefault(Calendar.YEAR, 0);
                            if (amount == 12)
                                durations.put(Calendar.YEAR, years - 1);
                            durations.put(Calendar.MONTH, amount - 1);
                            amount = dateTo.get(Calendar.DAY_OF_MONTH);
                            dateTo.add(Calendar.MONTH, -1);
                            max = dateTo.getActualMaximum(Calendar.DAY_OF_MONTH);
                            amount += max - Math.min(max, dateFrom.get(Calendar.DAY_OF_MONTH));
                        }
                        durations.put(Calendar.WEEK_OF_YEAR, amount / 7);
                        amount %= 7;
                    }
                }
```
`Switch statement can be replaced with enhanced 'switch'`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +            out.append((negative && entry.getValue() > 0 ? "-" : "") + entry.getValue() + " " + plural(entry.getValue(), names[accusative ? 1 : 0], names[2], names[3]));
```suggestion
            out.append(negative && entry.getValue() > 0 ? "-" : "").append(entry.getValue()).append(" ").append(plural(entry.getValue(), names[accusative ? 1 : 0], names[2], names[3]));
```
`String concatenation as argument to 'StringBuilder.append()' call`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +        final Calendar date = new GregorianCalendar();
`Obsolete date-time type 'Calendar' used`
`Obsolete date-time type 'GregorianCalendar' used`

2021-08-19 10:57 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +                date.add(type.getKey(), durations.remove(type.getValue().getLeft()));
`Should be one of: Calendar.ERA, Calendar.YEAR, Calendar.MONTH, Calendar.WEEK_OF_YEAR, Calendar.WEEK_OF_MONTH, ...`

2021-09-01 17:16 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Actions.java
> +    public static void muteMember(final @NotNull MessageChannel channel, final @NotNull Role role, final @NotNull Member author, final @NotNull Member muted, final String reason, int duration, String
```suggestion
public static void muteMember(final @NotNull MessageChannel channel, final @NotNull Role role, final @NotNull Member author, final @NotNull Member muted, final String reason, final long duration, String durationString, final boolean silent) {
```

2021-09-05 09:45 UTC, Apceniy commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +                    continue;
what's wrong?

2021-09-05 12:05 UTC, l1ttleO requested changes

2021-09-05 12:05 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +                max = (int) unit.getBaseUnit().getDuration().toMillis();
`Cast from 'long' to 'int' may result in loss of precision`

2021-09-05 12:05 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/commands/Remind.java
> +    public void run(final @NotNull MessageReceivedEvent event, final @NotNull String @NotNull [] args) throws NumberOverflowException, InvalidAuthorException, WrongUsageException {
`The declared exception 'NumberFormatException' is never thrown`

2021-09-05 12:05 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/commands/Mute.java
> +        else duration = 3600_000;
`Group in number literal with underscores does not have length 3`

2021-09-05 12:22 UTC, Apceniy commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +                max = (int) unit.getBaseUnit().getDuration().toMillis();
This line is called for hours, minutes and seconds. For hours it's 3600000, for minutes it's 60000, for seconds it's 1000. Precision can't be lost there.

2021-09-05 12:27 UTC, Apceniy commented on src/main/java/ru/l1ttleO/boyfriend/commands/Mute.java
> +        else duration = 3600_000;
I used it to separate seconds and milliseconds

2021-09-05 12:27 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/Utils.java
> +                max = (int) unit.getBaseUnit().getDuration().toMillis();
https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#toIntExact-long-

2021-09-05 12:30 UTC, Apceniy commented on src/main/java/ru/l1ttleO/boyfriend/commands/Remind.java
> +    public void run(final @NotNull MessageReceivedEvent event, final @NotNull String @NotNull [] args) throws NumberOverflowException, InvalidAuthorException, WrongUsageException {
Did you mean 'NumberOverflowException'?

2021-09-05 12:31 UTC, l1ttleO commented on src/main/java/ru/l1ttleO/boyfriend/commands/Remind.java
> +    public void run(final @NotNull MessageReceivedEvent event, final @NotNull String @NotNull [] args) throws NumberOverflowException, InvalidAuthorException, WrongUsageException {
...yes

2021-09-05 13:07 UTC, l1ttleO approved these changes
LGTM

2021-09-05 13:08 UTC, merged